on: [push, pull_request]
name: build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v1.7
        with:
          architecture: 'x64'
          distribution: 'full'
          version: 'current'
      - uses: GabrielBB/xvfb-action@v1
        with:
          run: raco test --drdr --timeout 240 .
